package com.example.covidtracker.Models

data class Tested(
    val dailyrtpcrsamplescollectedicmrapplication: String,
    val firstdoseadministered: String,
    val frontlineworkersvaccinated1stdose: String,
    val frontlineworkersvaccinated2nddose: String,
    val healthcareworkersvaccinated1stdose: String,
    val healthcareworkersvaccinated2nddose: String,
    val over45years1stdose: String,
    val over45years2nddose: String,
    val over60years1stdose: String,
    val over60years2nddose: String,
    val positivecasesfromsamplesreported: String,
    val registrationflwhcw: String,
    val registrationonline: String,
    val registrationonspot: String,
    val samplereportedtoday: String,
    val seconddoseadministered: String,
    val source: String,
    val source2: String,
    val source3: String,
    val source4: String,
    val testedasof: String,
    val testsconductedbyprivatelabs: String,
    val totaldosesadministered: String,
    val totalindividualsregistered: String,
    val totalindividualstested: String,
    val totalindividualsvaccinated: String,
    val totalpositivecases: String,
    val totalrtpcrsamplescollectedicmrapplication: String,
    val totalsamplestested: String,
    val totalsessionsconducted: String,
    val updatetimestamp: String
)